joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - positioner_joint
  gains:
    positioner_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
