robot1_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - rob1_joint_1
    - rob1_joint_2
    - rob1_joint_3
    - rob1_joint_4
    - rob1_joint_5
    - rob1_joint_6

  gains: # Required because we're controlling a velocity interface
    rob1_joint_1: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob1_joint_2: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob1_joint_3: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob1_joint_4: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob1_joint_5: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob1_joint_6: {p: 100, d: 0.0, i: 0, i_clamp: 0}

robot2_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - rob2_joint_1
    - rob2_joint_2
    - rob2_joint_3
    - rob2_joint_4
    - rob2_joint_5
    - rob2_joint_6

  gains: # Required because we're controlling a velocity interface
    rob2_joint_1: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob2_joint_2: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob2_joint_3: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob2_joint_4: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob2_joint_5: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob2_joint_6: {p: 100, d: 0.0, i: 0, i_clamp: 0}

robot3_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - rob3_joint_1
    - rob3_joint_2
    - rob3_joint_3
    - rob3_joint_4
    - rob3_joint_5
    - rob3_joint_6

  gains: # Required because we're controlling a velocity interface
    rob3_joint_1: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob3_joint_2: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob3_joint_3: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob3_joint_4: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob3_joint_5: {p: 100, d: 0.0, i: 0, i_clamp: 0}
    rob3_joint_6: {p: 100, d: 0.0, i: 0, i_clamp: 0}

positioner_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - rotary_table_positioner

  gains: # Required because we're controlling a velocity interface
    rotary_table_positioner: {p: 100, d: 0.0, i: 0, i_clamp: 0}