robot1_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - rob1_joint_1
    - rob1_joint_2
    - rob1_joint_3
    - rob1_joint_4
    - rob1_joint_5
    - rob1_joint_6

robot2_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - rob2_joint_1
    - rob2_joint_2
    - rob2_joint_3
    - rob2_joint_4
    - rob2_joint_5
    - rob2_joint_6

robot3_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - rob3_joint_1
    - rob3_joint_2
    - rob3_joint_3
    - rob3_joint_4
    - rob3_joint_5
    - rob3_joint_6

positioner_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - rotary_table_positioner