generic_hw_control_loop:
  loop_hz: 1000
  cycle_time_error_threshold: 0.01

hardware_interface:
  joints:
    - positioner_joint
  sim_control_mode: 0 # 0: position, 1: velocity

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
