controller_list:
  - name: robot1_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
      - rob1_joint_1
      - rob1_joint_2
      - rob1_joint_3
      - rob1_joint_4
      - rob1_joint_5
      - rob1_joint_6
  - name: robot2_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
      - rob2_joint_1
      - rob2_joint_2
      - rob2_joint_3
      - rob2_joint_4
      - rob2_joint_5
      - rob2_joint_6
  - name: robot3_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
      - rob3_joint_1
      - rob3_joint_2
      - rob3_joint_3
      - rob3_joint_4
      - rob3_joint_5
      - rob3_joint_6
  - name: positioner_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
      - positioner_joint
