controller_list:
  - name: fake_rob1_planning_group_controller
    type: $(arg fake_execution_type)
    joints:
      - rob1_joint_1
      - rob1_joint_2
      - rob1_joint_3
      - rob1_joint_4
      - rob1_joint_5
      - rob1_joint_6
  - name: fake_rob2_planning_group_controller
    type: $(arg fake_execution_type)
    joints:
      - rob2_joint_1
      - rob2_joint_2
      - rob2_joint_3
      - rob2_joint_4
      - rob2_joint_5
      - rob2_joint_6
  - name: fake_rob3_planning_group_controller
    type: $(arg fake_execution_type)
    joints:
      - rob3_joint_1
      - rob3_joint_2
      - rob3_joint_3
      - rob3_joint_4
      - rob3_joint_5
      - rob3_joint_6
  - name: fake_positioner_planning_group_controller
    type: $(arg fake_execution_type)
    joints:
      - positioner_joint
  - name: fake_hydra_planning_group_controller
    type: $(arg fake_execution_type)
    joints:
      - rob1_joint_1
      - rob1_joint_2
      - rob1_joint_3
      - rob1_joint_4
      - rob1_joint_5
      - rob1_joint_6
      - rob2_joint_1
      - rob2_joint_2
      - rob2_joint_3
      - rob2_joint_4
      - rob2_joint_5
      - rob2_joint_6
      - rob3_joint_1
      - rob3_joint_2
      - rob3_joint_3
      - rob3_joint_4
      - rob3_joint_5
      - rob3_joint_6
      - positioner_joint
initial:  # Define initial robot poses per group
  - group: rob1_planning_group
    pose: home
  - group: rob2_planning_group
    pose: home
  - group: rob3_planning_group
    pose: home
  - group: positioner_planning_group
    pose: home
  - group: hydra_planning_group
    pose: home