# Default initial positions for hydra's ros2_control fake system

initial_positions:
  rob1_joint_1: 0.0
  rob1_joint_2: 0.53
  rob1_joint_3: 0.47
  rob1_joint_4: 0.0
  rob1_joint_5: -1.0
  rob1_joint_6: 0.0
  rob2_joint_1: 0.0
  rob2_joint_2: 0.53
  rob2_joint_3: 0.47
  rob2_joint_4: 0.0
  rob2_joint_5: -1.0
  rob2_joint_6: 0.0