rob1_planning_group:
  kinematics_solver: hydra_rob1_planning_group/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005"
rob2_planning_group:
  kinematics_solver: hydra_rob2_planning_group/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
rob3_planning_group:
  kinematics_solver: hydra_rob3_planning_group/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
