rob1_planning_group:
  link_prefix: "rob1_"
  kinematics_solver: za_kinematics/IKFastKinematicsPlugin
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
rob2_planning_group:
  link_prefix: "rob2_"
  kinematics_solver: za_kinematics/IKFastKinematicsPlugin
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
rob3_planning_group:
  link_prefix: "rob3_"
  kinematics_solver: za_kinematics/IKFastKinematicsPlugin
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
positioner_planning_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
hydra_planning_group:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  mode: gd_c
