# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    rob1_planning_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    rob2_planning_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    rob3_planning_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    positioner_planning_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rob1_planning_group_controller:
  ros__parameters:
    joints:
      - rob1_joint_1
      - rob1_joint_2
      - rob1_joint_3
      - rob1_joint_4
      - rob1_joint_5
      - rob1_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
rob2_planning_group_controller:
  ros__parameters:
    joints:
      - rob2_joint_1
      - rob2_joint_2
      - rob2_joint_3
      - rob2_joint_4
      - rob2_joint_5
      - rob2_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
rob3_planning_group_controller:
  ros__parameters:
    joints:
      - rob3_joint_1
      - rob3_joint_2
      - rob3_joint_3
      - rob3_joint_4
      - rob3_joint_5
      - rob3_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
positioner_planning_group_controller:
  ros__parameters:
    joints:
      - positioner_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
